### ISSUE TITLE
Text Layer Overlay can't handle ALTO without ID attributes

### ISSUE THREAD

**Issue by benwbrum** [annotorious/annotorious-v3-extensions#1]
We ran into a strange problem working with ALTO files generated by Transkribus -- only the last word in the file was appearing as an annotation.  After looking at [the relevant code](https://github.com/annotorious/annotorious-v3-extensions/blob/a4bac98a797a0f6b658f819043c24395fde05ff9/annotorious-formats/src/alto/altoParser.ts#L62) and comparing the Transkribus-generated ALTO with the sample file, we determined that the Text Overlay depends on the presence of an `ID` attribute in the source ALTO files.  If no `ID` is present, all annotations will have an `id` of `null`, so each word parsed from the ALTO one overwrites the previous annotation.

We were able to [address this on the server side](https://github.com/benwbrum/fromthepage/blob/development/app/controllers/page_controller.rb#L22-L33) in FromThePage, so there is no urgency in fixing this from us.

Example file: 
[example_alto.zip](https://github.com/annotorious/annotorious-v3-extensions/files/13753134/example_alto.zip)

**Comment by rsimon** [comment]
Yikes. One of those small things that break stuff when you're not expecting them. I added a small fix that will also address this on the client. (It will fill in an ad-hoc UUID if no ID is present.) After the fix, I got the attached sample file to display correctly.

But don't deploy any of this yet. I have a new release of Annotorious coming up (hopefully the one with the final API for v3.0.0...), and there are some mini breaking changes. (One function name relevant for you has changed, and "formatters" are now called, simply "styles".) I'll update the example and let you know once the new release is out. (Might happen later today - or mid next week.)

**Comment by rsimon** [comment]
Hi @benwbrum,

I got the new release out for Annotorious. (Fingers crossed that those are the last breaking changes!) Either way: I made the necessary tweaks to make everything work with the most recent Annotorious version. As you will see, the changes you need to make on your end are minimal.

The only change is how Annotorious is initialized. Here's how this works now:

```js
var anno = AnnotoriousOSD.createOSDAnnotator(viewer, {
  pointerSelectAction: 'NONE',
  style: {
    fillOpacity: 0,
    strokeOpacity: 0
  }
});
```

The old version was:

```js
var anno = AnnotoriousOSD.createOSDAnnotator(viewer, {
  pointerSelectAction: 'NONE'
});

anno.setFormatter(function() { 
  return { fillOpacity: 0 };
});
```

Explanation:
- 'Formatters' are now called, simply, style. Styles are responsible for how the annotation boxes appear. In your case, you want to hide them. Therefore, you need to set both `fillOpacity` and `strokeOpacity` to `0`. 
- Annotorious now supports setting the style right on initialization. Therefore, an extra call to `.setStyle` (previously `.setFormatter`) is no longer needed.

**Comment by benwbrum** [comment]
I believe that this can be closed.
